Word duplication during merge bug
nkowaokwu/igbo-api-admin pull request #112
Opened 2022-09-10 13:54 UTC by Robertito1

| Status  | Type  | Env Vars Change | Ticket |
| :---: | :---: | :---: | :--: |
| Ready | Bug | Yes | Closes N/A |

## Problem

_What problem are you trying to solve?_
Words were getting duplicated when the word suggestion was supposed to be merged, this was caused because sometimes when trying to merge a word, the original word id will not be included in the suggestion doc thereby causing the program to create an entirely new word

## Solution

_How did you solve the problem?_
Added the original word Id to the body of the request that creates a new word or updates an existing one.

2022-09-10 14:42 UTC, ijemmao requested changes

2022-09-10 14:42 UTC, ijemmao commented on src/shared/API.ts
> +  data: { id: record.id, originalWordId: record.originalWordId ? record.originalWordId : null },
@Robertito1 i think this logic of checking if the document has an original word I'd should happen on the backend

So when we call this endpoint, the function that gets called in the back end should make this check.

This can lead to a security vulnerability where a bad actor could put in any invalid original word Id to overwrite theerged documents original word Id in the database 

The reason why I don't think this line is the solution is because this line hadn't changed for more than a year, and the duplication problem started recently (after i did the large database migration for sufficient words to be only available to the public)

2022-09-10 16:01 UTC, Robertito1 commented on src/shared/API.ts
> +  data: { id: record.id, originalWordId: record.originalWordId ? record.originalWordId : null },
Honestly I think you're right, I came up with this fix without really experiencing the bug firsthand, now the error message that Obioha complained about can only get thrown when the code is trying to create an entirely new word entry, this should not be so if the word being merged is already existing. I will check the possibility of fixing this from the backend

2022-09-10 22:16 UTC, Robertito1 commented
@ijemmao please take a look at this again when you can

2022-09-10 22:59 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +      return await packageResponse({
There's no need to await this return value since it's going to be resolved by express!

2022-09-10 22:59 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
@Robertito1 we're you able to identify why the original word Id isn't appearing for certain suggestions?

Making an extra query to merge a word will lead to a performance hit, so i wanna see if we could have another solution as an alternative

2022-09-11 00:01 UTC, Robertito1 commented on src/backend/controllers/words/index.ts
> +      return await packageResponse({
That's true but Typescript was throwing an error because of it

2022-09-11 00:04 UTC, Robertito1 commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
You are correct, this is just a fail safe I'm sure the mix up of the original word id not being in the `suggestionDoc` is somewhere else.

I haven't been able to reproduce this issue locally which would have made it easy to locate the root cause of this problem

2022-09-11 13:41 UTC, Robertito1 commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
@ijemmao A suggestion is that we could use this to curtail the immediate setback the bug is causing and then open a ticket till I can find the root cause of this bug

2022-09-11 17:12 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
hmm, i don't think it's worth adding an extra query to a system that's already slow - i think we should take time to identify the root cause of the issue so we can have the right solution. this way we don't have revisit this in the future

2022-09-11 17:14 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
one test you can do to see is to create a new word suggestion from an existing word document, then remove the word suggestions `originalWordId` value and then attempt to merge it - i wonder if the document will begin to duplicate

also - you can ask the translators when they do notice a duplicate, ask them to send a link to the word so you can look at all the word's attributes and see if there's something within the document that's causing a duplicate

2022-09-11 20:29 UTC, Robertito1 commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
Yeah I tried this, I removed the `originalwordId` from a word suggestion I created, and it duplicated the word.

2022-09-11 20:31 UTC, Robertito1 commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
Okay it's cool, we will wait till we are able to find to root cause of this bug

2022-09-13 13:37 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
in the meantime can you close this PR?

2022-09-13 13:37 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +    }: Document<Interfaces.WordSuggestion> | any = await WordSuggestion.findById(suggestionDoc.id);
and then update the team that you are trying to find the root cause of the bug?

2022-09-14 01:53 UTC, closed without merging