Constructed terms tab
nkowaokwu/igbo-api-admin pull request #129
Opened 2022-09-25 16:57 UTC by Robertito1

| Status  | Type  | Env Vars Change | Ticket |
| :---: | :---: | :---: | :--: |
| Ready | Feature | No | Closes #113 |

## Problem

_What problem are you trying to solve?_
The platform editors are compiling words that are constructed separately and storing them in a spread sheet, this solution is not ideal because of the extra work required to keep track of it, this approach is also prone to data loss and inaccuracy.

## Solution

_How did you solve the problem?_
We are storing the constructed terms data in a new tab on the editor platform, with this it will be easier to know what words need to be sent out in the polls and all the editors will have access to this words

## Before & After Screenshots

**BEFORE**:
![Screenshot from 2022-09-25 17-40-18](https://user-images.githubusercontent.com/60134828/192154992-47cc1845-1837-4ac9-87b0-c03e14977993.png)

**AFTER**:
![Screenshot from 2022-05-18 09-36-04](https://user-images.githubusercontent.com/60134828/192155040-c83176f7-d5ed-416f-b15b-eba52ee6a1f2.png)
![Screenshot from 2022-09-25 17-37-06](https://user-images.githubusercontent.com/60134828/192155041-396d221e-583d-4d42-8904-52068d0f5efe.png)
![Screenshot from 2022-09-25 17-37-16](https://user-images.githubusercontent.com/60134828/192155042-d5309311-6ef0-4253-a59c-815657f72b64.png)
![Screenshot from 2022-09-25 17-37-33](https://user-images.githubusercontent.com/60134828/192155043-bc3b2a9b-b100-40b0-8825-4cc0081c80da.png)
![Screenshot from 2022-09-25 17-37-49](https://user-images.githubusercontent.com/60134828/192155044-f6d32f59-1baa-4913-be66-de21e45dcf34.png)
![Screenshot from 2022-09-25 17-38-00](https://user-images.githubusercontent.com/60134828/192155045-b2b047e9-6042-4067-892d-7cd6dcbced6f.png)

2022-09-25 22:47 UTC, ijemmao requested changes

2022-09-25 22:47 UTC, ijemmao commented on src/App/IgboAPIAdmin.tsx
> +              {...hasAdminPermissions(permissions, true)
why would we want to apply admin permissions for creating new terms?

2022-09-25 22:47 UTC, ijemmao commented on src/backend/controllers/utils/HandleQueriesType.ts
> +  constructedTerms: boolean,
are we able to put `constucutedTerms` inside of `filters` instead?

2022-09-25 22:47 UTC, ijemmao commented on src/backend/controllers/utils/buildDocs.ts
> +  match = constructedTerms ? { ...match, 'attributes.isConstructedTerm': { $eq: true } } : match;
yeah, i don't think we want to expand what `buildDocs` does for this case, rather we would want this be handled in the `queries` file

2022-09-25 22:47 UTC, ijemmao commented on src/backend/controllers/words/index.ts
> +  const words: Interfaces.Word[] = await findWordsWithMatch({ match: query, constructedTerms, ...rest });
let's avoid expanding the API for `buildDocs` - I don't think any of these functions need to change in functionality actually

2022-09-25 22:47 UTC, ijemmao commented on src/backend/routers/apiRouter.tsx
> +apiRouter.get('/constructedTerms/:id', getWord);
the `apiRouter` loosely matches the `apiRouter` used in the Igbo API, since we only want editors and admins to be able to view constructed terms, we would want these routes to live in `editorRouter`

2022-09-25 22:47 UTC, ijemmao commented on src/backend/routers/editorRouter.tsx
> +  authorization([UserRoles.MERGER, UserRoles.ADMIN]),
similar question as before by why are you applying these permission restrictions to only allow mergers and admins to create terms?

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
we would want constructed terms to follow the same path as regular words, so we would need constructed terms to be merge-able, you can remove this line change~

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/Select/Select.tsx
> +    resource === Collection.CONSTRUCTED_TERMS ? null : {
similar in this case, we would want people to be able to approve or deny constructed terms

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
let's revert this change as well

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/actions/ListActions.tsx
> +        {isPollResource || isConstructedTermResource ? null : (
we wouldn't want to skip constructed terms here since we need to be able to paginate between pages

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/actions/ListActions.tsx
> +        {isPollResource || isUserResource || isConstructedTermResource ? null : (
we can also revert this line since we want to take advantage of filtering for constructed terms

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/views/components/WordEditForm/WordEditForm.tsx
> +          isConstructedTerm ? '/constructedTerms' : '/wordSuggestions',
are we able to use the `resource` variable to place that here instead of using this ternary?

2022-09-25 22:47 UTC, ijemmao commented on src/shared/components/views/components/WordEditForm/components/HeadwordForm/HeadwordForm.tsx
> +                    isChecked={isConstructedTerm ? true : value}
nit: this can rewritten as `isConstructedTerm || value`

2022-09-26 10:31 UTC, Robertito1 commented on src/App/IgboAPIAdmin.tsx
> +              {...hasAdminPermissions(permissions, true)
My thinking was that even though these terms are accepted and reviewed by the whole community creating new ones is not something that should be done without a go ahead, but we can always remove the restriction

2022-09-26 10:32 UTC, Robertito1 commented on src/backend/routers/editorRouter.tsx
> +  authorization([UserRoles.MERGER, UserRoles.ADMIN]),
Yeah answered the first one you asked

2022-09-26 10:35 UTC, Robertito1 commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
I have a question about is, so can we think of the "Constructed terms" as new words or should they be thought of as word suggestions

2022-09-27 19:37 UTC, ijemmao commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
yeah~

2022-09-27 22:42 UTC, Robertito1 commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
Hi Ijemma, it's still a bit unclear which you are affirming to, the reason I'm asking is because if the constructed term is considered a part of the words then what are we merging it to become, and if it's supposed to be considered part of a word suggestion then we should probably store it as a word suggestion document

2022-09-28 13:21 UTC, ijemmao commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
constructed terms are word suggestions. the reason for this is because word suggestions have a checkbox option Is Constructed. So newly created Constructed terms are just word suggestions that have the Is Constructed Term option checked

the focus for this PR is to create a new list view for Word Suggestions that have the Is Constructed Term option selected making them constructed terms

this means that there shouldn't be any new schemas or data concepts for constructed terms, rather we just want to have options selected by default

2022-09-28 13:21 UTC, ijemmao commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
now that i think about it, i think we can just add a new word suggestion filter that is Constructed

2022-10-01 21:30 UTC, Robertito1 commented on src/shared/components/Select/Select.tsx
> +    hasAdminOrMergerPermissions(permissions, (record.merged || resource === Collection.CONSTRUCTED_TERMS ? null : [
Understood :100: I dont know what gave me the impression that a constructed term will be an actual word document with the `isConstructedTerm` field as `true`. Anyways I get it clearly now and I have effected all the changes you have requested, except for adding the filters in the request that fetches the constructed term. Is the search functionality of the system is quite complex, I'm still looking at it, just thought to let you know of the progress if you want to check it out

2022-10-04 01:46 UTC, ijemmao commented on src/backend/controllers/constructedTerms.ts
> +    }
we would want to use a middleware function to make these checks. alongside using something like `joi` for data schema validation

2022-10-04 01:46 UTC, ijemmao commented on src/backend/controllers/constructedTerms.ts
> +export const putConstructedTerm = async (
could we just use the putWordSuggestion function since ConstructedTerms are just WordSuggestions?

2022-10-05 02:02 UTC, Robertito1 commented on src/backend/controllers/constructedTerms.ts
> +    }
That's true, I have included the Middleware checks for the constructed terms,  I will convert the Middleware to a `joi`managed one

2022-10-05 12:46 UTC, ijemmao requested changes

2022-10-05 12:46 UTC, ijemmao commented on src/backend/middleware/validateConstructedTermBody.ts
> +};
let's use `joi` for this validation step!

2022-10-05 12:46 UTC, ijemmao commented on src/backend/controllers/constructedTerms.ts
> +};
so in theory, this function wouldn't need to exist since we already have a similar function for getting word suggestions. instead what we would want to do is on the client side, pass along the `isConstructedTerm` filter so that we are always getting the correct word suggestions

2022-10-05 12:46 UTC, ijemmao commented on src/backend/controllers/constructedTerms.ts
> +    }
would you want to use the `validatedConstructedTerms` middleware for this?

2022-10-08 14:44 UTC, ijemmao requested changes

2022-10-08 14:44 UTC, ijemmao commented on package.json
> +    "joi": "^17.6.2",
sorry i know i say `joi`, but i think we can just use `yup`

2022-10-10 13:16 UTC, Robertito1 commented
@ijemmao I'm closing this pull request since we took a different route

2022-10-10 13:16 UTC, closed without merging