chore: redesign Leaderboard page
nkowaokwu/igbo-api-admin pull request #438
Opened 2023-08-07 21:42 UTC by IfyNdu

| Status  | Type  | Env Vars Change | Ticket |
| :---: | :---: | :---: | :--: |
| Ready|Refactor|No | Closes #429 |

## Problem
User interface redesign

## Solution
Refactored `<Leaderboard />` component to match new figma designs

## GIF

![Aug-07-2023 22-08-11](https://github.com/nkowaokwu/igbo-api-admin/assets/15639127/3eb4b6f6-1ce4-48fc-9c11-a1b5365c8b6a)

## VIDEO
https://github.com/nkowaokwu/igbo-api-admin/assets/15639127/a120a9d7-f926-44c5-a192-c8db486f1eb8

## QA

  

## Other changes (e.g. bug fixes, UI tweaks, small refactors)
- [x] Refactored. existing logic a wee bit to simplify new logic
- [x] Created an Icon house which will provide a structural approach for consuming icons in a consistent format
- [x] Separated out renderer config from Leaderboard file to reduce Component bloating
- [x] Updated `eslint max-length` to ignore `html.path` `d` attribute as they cannot be broken into template strings. Existing `eslint max-length` ignore rule can be refactored with `prettier`

2023-08-07 22:33 UTC, ijemmao requested changes
this is absolutely amazing 🤩 the functionality is really solid, just a couple comments on code quality:
* Remove all the extra comments (i'm happy to see code deleted!)
* Use Chakra variables everywhere, especially for colors
* Let's avoid placing called functionality components in objects

2023-08-07 22:33 UTC, ijemmao commented on .eslintrc.json
> -    "max-len": ["error", { "code": 120, "ignorePattern": "^import\\W.*" }],
what's the reason for this change?

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +// import { Box, IconButton, Grid, Heading, Select, Text, Tooltip, useToast, chakra } from '@chakra-ui/react';
delete this comment if we don't need it

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +// };
delete this comment and any other commented out code

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +            icon={<Icons.ArrowBack width={6} height={6} stroke="rgba(39, 39, 39, 1)" />}
instead of passing in raw rgba strings, let's pass in Chakra variables: https://chakra-ui.com/docs/styled-system/css-variables

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +        <Box bg={leaderboardItem?.styles?.bgColor} w="100%" p={2} fontFamily="Silka">
nit: the conditional `?.` don't need to be added if the `leaderboardItem` is already confirmed to exist - this assumes that every leaderboard item should has a styles object

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/components/LeaderboardItem.tsx
> +export const LeaderboardItem: React.FC<Props> = ({ Icon, title }) => (
learned something new with `React.FC`!

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +      color: 'rgba(39, 39, 39, 1)',
we don't want to use raw strings since it's harder to maintain colors according to our Chakra-defined theme

you can use Chakra variables to get the colors you want

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +        Icon={<Icons.Microphone stroke="rgba(255, 121, 0, 1)" />}
same comment about using variables instead of raw strings for styling

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/iconography/Microphone.tsx
> +  stroke = 'grey',
use Chakra UI variables like `gray.500`

this comment applies to all the icons in this directory

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +    }
nit: readability is easier if we just check to see if the index isn't null

```suggestion
  if (leaderboardIndex !== null) {
      handleRequestingLeaderboard();
    }
```

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +  const [leaderboardIndex, setLeaderboardIndex] = useState<number | null>();
for clarity, instead of this being a number, it should be a `LeaderboardType`

```suggestion
  const [selectedLeaderboard, setSelectedLeaderboard] = useState<LeaderboardType | null>(null);
```

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +  const handleLeaderboardClick = (index: number) => () => {
instead of passing in the index of the leaderboard, pass in the `leaderboard.uid` which should be the type `LeaderboardType`

```suggestion
  const handleLeaderboardClick = (leaderboardId: LeaderboardType) => () => {
```

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +      setLeaderboardIndex(index);
you don't need to check to see if the uid is selected already, you can just call setSelectedLeaderboard

```suggestion
    setSelectedLeaderboard(leaderboardId);
```

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +      {leaderboardItem && (
nit: we don't want to use `&&` for conditionally rendering components since that might lead to unintended data to get rendered

ref: https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +    ),
it feels a bit odd to have functional components being called within object, instead you can just have the props that would be passed into the `LeaderboardItem` component as fields in this object (this way you can remove the `children` object

```suggestion
    icon: Done,
    title: titleMap[VERIFY_EXAMPLE_AUDIO],
```
let me know if you have any questions

2023-08-07 22:33 UTC, ijemmao commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +  },
the exciting thing about working on this project is having live users! one thing that we want to make sure that we do is introduce changes that doesn't disrupt our users' expectations on the platform

so rn a lot of our users are participating in the Igbo Voice-athon and they really only care to know how many sentences they've recorded.

let's move this option to the top of this list so its the first option our users see when they navigate to this page

2023-08-07 22:35 UTC, ijemmao requested changes

2023-08-07 22:35 UTC, ijemmao commented on src/Core/Collections/Leaderboard/components/SearchBar.tsx
> +  onChange?: (p: { value: string }) => void;
`onChange` should be required

2023-08-07 22:35 UTC, ijemmao commented on src/Core/Collections/Leaderboard/components/SearchBar.tsx
> +    onChange && onChange({ value: target.value });
remove this onChange check

```suggestion
  onChange({ value: target.value });
```

2023-08-07 22:35 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +      <SearchBar />
we have real users on the platform, so we can't release anything that's not functional

feel free to:
1. comment out this line of code
2. create a follow up ticket to implement the functionality of this search bar (honestly i don't really know how this search bar is going to work since we have multiple leaderboards - this is something you can ask David)

2023-08-08 16:50 UTC, IfyNdu commented on .eslintrc.json
> -    "max-len": ["error", { "code": 120, "ignorePattern": "^import\\W.*" }],
Updated `eslint max-length` to ignore `d` attribute of `html.path`  `<path d="M3.65641 2.65..." />` as they cannot be broken into template strings. imports can easily be refactored to spread across multiple lines. Unfortunately `ignorePattern` here can only take a single condition

2023-08-08 16:51 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +            icon={<Icons.ArrowBack width={6} height={6} stroke="rgba(39, 39, 39, 1)" />}
Thanks for this suggestion. I was looking for how to do this

2023-08-08 16:58 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +            icon={<Icons.ArrowBack width={6} height={6} stroke="rgba(39, 39, 39, 1)" />}
@ijemmao 
Do we have a design system i could use to introduce new colours to the codebase?

2023-08-08 17:01 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +        <Box bg={leaderboardItem?.styles?.bgColor} w="100%" p={2} fontFamily="Silka">
Very good catch!

2023-08-08 17:14 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +      <SearchBar />
1. _comment out this line of code_: I will delete this line for now, i'm not a fan of leaving dangling comments about.
2. I think it is supposed to be active once a leaderboard option is selected. I believe it was inadvertently placed on the Leaderboards page.

2023-08-08 17:19 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +  },
Refactored! Thanks for pointing this out. I followed the ordering on Figma without checking what is deployed.

2023-08-08 17:32 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +  const [leaderboardIndex, setLeaderboardIndex] = useState<number | null>();
I wouldn't want to do an `Array.find` each time i need to access the selected LeaderboardItem. Using an index runs `O(1)`. For the sake of clarity I will update this to be the actual selected leaderboard object.

2023-08-08 17:40 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +  const handleLeaderboardClick = (index: number) => () => {
Reason for not passing a uid is covered here https://github.com/nkowaokwu/igbo-api-admin/pull/438#discussion_r1287448199 will store the leaderboard option config instead.

2023-08-08 17:51 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +      {leaderboardItem && (
I am happy to refactor to ternaries if thats what you guys are comfortable with. Conditional rendering will only yield unexpected results if you fail to provide an actual condition that returns a boolean.

2023-08-08 17:58 UTC, IfyNdu commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +    ),
This implementation satisfies the `O` in `SOLID` principle moreover it makes the component very flexible. Material UI adopts this composition type architecture for their framework.

2023-08-09 13:57 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +            icon={<Icons.ArrowBack width={6} height={6} stroke="rgba(39, 39, 39, 1)" />}
Here is our [ChakraTheme.ts](https://github.com/nkowaokwu/igbo-api-admin/blob/main/src/App/ChakraTheme.ts) file responsible for defining the colors, styles, sizes, etc. that we use throughout the app for consistent styling

here's an example where we're using the `gray.600` Chakra UI variable value for a gray: https://github.com/nkowaokwu/igbo-api-admin/blob/main/src/Core/Collections/IgboSoundbox/VerifySentenceAudio.tsx#L176

instead of directly using the `#4F4F4F` equivalent, we want to use `gray.600` so if we decide we don't want to use `#4F4F4F` for all our `gray.600` we can change it in the `ChakraTheme.ts` file and that will affect all usages of `gray.600`

2023-08-09 13:59 UTC, ijemmao commented on src/Core/Collections/Leaderboard/Leaderboard.tsx
> +      {leaderboardItem && (
yeah, let's use ternary for readability and to ensure that if we do forget to provide proper fallback values, we can be confident we don't return anything but `null`

2023-08-09 14:03 UTC, ijemmao commented on src/Core/Collections/Leaderboard/config/leaderboardItems.tsx
> +    ),
sounds good to me!

2023-08-14 12:10 UTC, ijemmao requested changes
real close! just one comment

2023-08-14 12:10 UTC, ijemmao commented on src/App/ChakraTheme.ts
> +      900: '#bd00ff',
nit: use uppercase  - i.e. `#F8E6FF`

2023-08-14 21:43 UTC, ijemmao approved these changes
looks great!

2023-08-14 21:48 UTC, merged