feat: expose create referral endpoint
nkowaokwu/igbo-api-admin pull request #481
Opened 2023-10-13 01:07 UTC by IfyNdu

| Status  | Type  | Env Vars Change | Ticket |
| :---: | :---: | :---: | :--: |
| Ready| Feature | No | Closes #456  |

## Problem
Implement a referral system as a means to provide an incentive to drive traffic to igbo api admin platform

## Solution
Exposed an endpoint which creates a relationship between a referrer and a referred user.
  
## QA
- [x] Unit test

2023-10-17 00:39 UTC, ijemmao requested changes
looks really good!!

2023-10-17 00:39 UTC, ijemmao commented on src/shared/DataCollectionAPI.ts
> +    params: { 'referral-code': '86HFJM' },
why is referral-code hardcoded?

2023-10-17 00:39 UTC, ijemmao commented on src/shared/DataCollectionAPI.ts
can you write a test to make sure that this request method is getting called with the correct params?

2023-10-17 00:39 UTC, ijemmao commented on src/backend/controllers/utils/interfaces.ts
> +    'referral-code'?: string;
can we have this be `referralCode` instead of `referral-code` since we're using `referralCode` later in the code?

2023-10-18 00:53 UTC, IfyNdu commented on src/shared/DataCollectionAPI.ts
> +    params: { 'referral-code': '86HFJM' },
Oops my bad! it is test code. There should be no FE changes in this PR. I have refactored it..

2023-10-21 20:40 UTC, ijemmao approved these changes

2023-10-25 21:26 UTC, ijemmao requested changes
looking really good 🤩

2023-10-25 21:26 UTC, ijemmao commented on src/backend/routers/crowdsourcerRouter.ts
> +crowdsourcerRouter.post(`/${Collection.USERS}/referral`, createReferral);
nit: can this line come after the `crowdsourcerRouter.get(`/${Collection.USERS}/referral`, findReferralCode);`

2023-10-25 21:26 UTC, ijemmao commented on src/backend/controllers/utils/interfaces.ts
> +  referredUserId: Crowdsourcer;
shouldn't `referrerId` and `referredUserId` be strings?

2023-10-25 21:26 UTC, ijemmao commented on src/backend/controllers/crowdsourcer/crowdsourcer.ts
> +    res.status(403).send({ error: `Users cannot be referred twice. Referral code [${referralCode}] will be ignored` });
nit: we can remove the [] around `referralCode`

2023-10-25 21:26 UTC, ijemmao commented on src/backend/controllers/crowdsourcer/crowdsourcer.ts
> +  const existingReferral = await Referral.findOne({ referredUserId: referredUser.id });
instead of using the document Ids, we want to use the Firebase uid to make it easier to look up specific users
```suggestion
  const existingReferral = await Referral.findOne({ referredUserId: referredUser.firebaseId });
```

2023-11-05 11:52 UTC, IfyNdu commented on src/backend/routers/crowdsourcerRouter.ts
> +crowdsourcerRouter.post(`/${Collection.USERS}/referral`, createReferral);
refactored, Thanks!

2023-11-05 12:05 UTC, IfyNdu commented on src/backend/controllers/utils/interfaces.ts
> +  referredUserId: Crowdsourcer;
Technically they are strings but it is better to use the representation which will consume. Have a look [here](https://www.mongodb.com/docs/drivers/node/current/fundamentals/typescript/) for official examples.

2023-11-05 12:25 UTC, IfyNdu commented on src/backend/controllers/crowdsourcer/crowdsourcer.ts
> +  const existingReferral = await Referral.findOne({ referredUserId: referredUser.id });
I would push back on this here. We don't want to tightly couple our internal `Crowdsourcer` usage with firebase as it wont provide portability and other issues in the future. Firebase id is merely a bridge between firebase auth and `Crowdsourcer` hence it should serve no other purpose. Besides it was described here in the [tech documentation](https://docs.google.com/document/d/1rP9LiRbWmVWxlGsr3PKxcP8_PL9Y7Siuy1MUfkGrLHM/edit#heading=h.6mj7fbesgj10) prior to implementation.

2023-11-05 12:36 UTC, IfyNdu commented on src/backend/controllers/crowdsourcer/crowdsourcer.ts
> +  const existingReferral = await Referral.findOne({ referredUserId: referredUser.id });
Specific users can be looked up using a [$lookup aggregation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/lookup/) query

2023-11-08 14:00 UTC, ijemmao commented on src/backend/controllers/crowdsourcer/crowdsourcer.ts
> +  const existingReferral = await Referral.findOne({ referredUserId: referredUser.id });
Thanks for mentioning the design document! I definitely missed that point. However, using the Firebase Id has been a consistent pattern across all our projects and has shown to scale very well since we depend on the unique user ids that are already generated to prevent duplicating the concept of having a 1:1 relationship between a distinct user and their identification code. If we use the Crowdsourcer Id to associate with a user, then we are duplicating this relationship which can lead to more code complexity or maintainance. Could you explain more in detail what you mean by "it won't provide portability and other issues in the future" specifically?

Additionally, `$lookup` aggregation has performance concerns that only really arise when we have the alternative of being able to create simplistic queries that use fields that are indexed without the extra lookup step.

2023-11-09 13:58 UTC, IfyNdu commented on src/backend/controllers/crowdsourcer/crowdsourcer.ts
> +  const existingReferral = await Referral.findOne({ referredUserId: referredUser.id });
To elaborate further on`'it won't provide portability and other may cause other issues in the future'` i meant if we decide to pick a different authentication provider in the future (given how often software changes) it would be difficult to update the changes across the entire project. It may even involve a db migration. However decoupling `Crowdsourcer` id from firebase id will provide flexibility in the future. If firebase id is already implemented project wide then i guess it only makes sense to be consistent.

Gotcha!

2023-11-13 14:11 UTC, ijemmao approved these changes

2023-11-13 14:11 UTC, merged