feat: display crowdsourcer referral code in profile section
nkowaokwu/igbo-api-admin pull request #502
Opened 2023-11-05 16:55 UTC by IfyNdu

| Status  | Type  | Env Vars Change | Ticket |
| :---: | :---: | :---: | :--: |
| Ready| Feature | No | Closes #482  |

## Problem

Give user's access to their referral code

## Solution

Render referral code in user's profile page and provide a copy functionality for UX purposes.

## Before & After Screenshots
![Screenshot 2023-11-05 at 16 46 46](https://github.com/nkowaokwu/igbo-api-admin/assets/15639127/c3d50762-16a4-4462-aa23-09c7da1405b0)
  
## QA

  

## Other changes (e.g. bug fixes, UI tweaks, small refactors)
  
Made `axios instance` client flexible enough to return an actual response data type if specified.

2023-11-08 14:03 UTC, ijemmao requested changes

2023-11-08 14:03 UTC, ijemmao commented on src/Core/Dashboard/components/RefferalCode/RefferalCode.tsx
> +  };
could you do something like this?:
```suggestion
  const onCopyReferralCode = () => {
    if (referralCode) {
      copyToClipboard({
        copyText: referralCode
      });
    }
  };
```

2023-11-08 14:03 UTC, ijemmao commented on src/Core/Dashboard/components/RefferalCode/RefferalCode.tsx
> +  }, []);
nit: move `useEffect` closest to the `return` statement for the component, just a pattern to keep component definitions somewhat consistent

2023-11-08 14:03 UTC, ijemmao commented on src/shared/utils/request.ts
> +export const request = async <T = any>(requestObject: AxiosRequestConfig): Promise<AxiosResponse<T>> => {
what's the purpose of doing `<T = any>`? could we just do `<T>`?

2023-11-08 14:03 UTC, ijemmao commented on src/shared/utils/request.ts
> +  return axios.request<T>({
ah! this is really important, thanks for adding this generic here, I can create a ticket to have generics be added to all `request` usage

2023-11-09 13:59 UTC, IfyNdu commented on src/shared/utils/request.ts
> +  return axios.request<T>({
Yup once they are added the `any` can be removed.

2023-11-09 14:09 UTC, IfyNdu commented on src/Core/Dashboard/components/RefferalCode/RefferalCode.tsx
> +  };
refactored, Thanks!

2023-11-09 14:49 UTC, ijemmao approved these changes

2023-11-09 14:49 UTC, merged